name: Metrics

on:
  repository_dispatch:
    types: [test_trigger]
  workflow_dispatch:
  schedule:
  - cron: '0 10,12,20 * * *'


jobs:
  github-metrics:
    name: Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          # 他のオプション。
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 14
          plugin_reactions_details: count, percentage
          plugin_reactions_ignored: bot
          plugin_achievements: yes
          plugin_achievements_threshold: B 
          plugin_achievements_secrets: yes
          plugin_achievements_ignored: octonaut
          plugin_achievements_limit: 0
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_attachments: yes
          plugin_tweets_limit: 4
          plugin_tweets_user: .user.twitter
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_limit: 4
          plugin_music_played_at: yes
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_repositories: yes
          plugin_repositories_featured: freeserverproject/freeserver-wiki, Nakatai-0322/Nakatai-0322, Nakatai-0322/Nakatai-0322.github.io
          plugin_rss: yes
          plugin_rss_source: https://nakatai-0322.hatenablog.jp/rss
          plugin_rss_limit: 6                               # Limit to 6 items
